#server:
# port: 8080
# servlet:
#   context-path: /mechyam

#spring:
# datasource:
#   url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
 #   username: ${DB_USERNAME}
  #  password: ${DB_PASSWORD}
# driver-class-name: com.mysql.cj.jdbc.Driver
 # redis:
#  host: ${REDIS_HOST}
 #   port: ${REDIS_PORT}


#management:
# endpoints:
 #   web:
  #    exposure:
   #     include: health,mappings
   
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /mechyam   # ðŸ”‘ VERY IMPORTANT

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,mappings 

  endpoint:
    health:
      show-details: always

